spring:
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/brickshop
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging: #https://www.baeldung.com/spring-boot-logging
  level:
    com.brickshop.services.*: DEBUG